// File Automatically generated by the ROOT Script Compiler 

#ifdef __CINT__

#pragma link C++ nestedclasses;
#pragma link C++ nestedtypedefs;

#pragma link C++ defined_in "/Users/aogaki/WorkSpace/tpc-track/tpcanalysis-main/./runmacro_mini.cpp";

#endif
